# Generated by Django 4.0.1 on 2022-01-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='user',
        ),
    ]
