# Generated by Django 4.0.1 on 2022-01-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_created_by_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='user',
        ),
    ]
